### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by davidfarinha** [jaredhanson/passport-google-oauth2#48] opened 2018-08-22 22:06 UTC
Lack of TypeScript typings (index.d.ts) bundled with this package, or through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by umidbekkarimov** [comment] 2019-02-08 11:51
For fellow googlers:

```ts
declare module "passport-google-oauth" {
  import { Strategy } from "passport";

  export interface OAuth2StrategyOptions {
    /**
     * Your Google application's client id.
     */
    clientID: string;

    /**
     * Your Google application's client secret.
     */
    clientSecret: string;

    /**
     * URL to which Google will redirect the user after granting authorization.
     */
    callbackURL: string;
  }

  /**
   * `Strategy` constructor.
   *
   * The Google authentication strategy authenticates requests by delegating to
   * Google using the OAuth 2.0 protocol.
   *
   * Applications must supply a `verify` callback which accepts an `accessToken`,
   * `refreshToken` and service-specific `profile`, and then calls the `cb`
   * callback supplying a `user`, which should be set to `false` if the
   * credentials are not valid.  If an exception occured, `err` should be set.
   *
   * Examples:
   *
   *     passport.use(new GoogleStrategy({
   *         clientID: '123-456-789',
   *         clientSecret: 'shhh-its-a-secret'
   *         callbackURL: 'https://www.example.net/auth/google/callback'
   *       },
   *       function(accessToken, refreshToken, profile, cb) {
   *         User.findOrCreate(..., function (err, user) {
   *           cb(err, user);
   *         });
   *       }
   *     ));
   */
  export class OAuth2Strategy extends Strategy {
    public constructor(
      options: OAuth2StrategyOptions,
      verify: <TProfile, TUser>(
        accessToken: string,
        refreshToken: string,
        profile: TProfile,
        cb: (err: null | Error, user: TUser) => void,
      ) => void,
    );
  }
}
```

**Comment by johnjensenish** [comment] 2019-03-21 21:45
Looks like there is a [`@types/passport-google-oauth2` package ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/passport-google-oauth2). Adding the profile and user types as @umidbekkarimov shows above would be an improvement.

**Comment by ezintz** [comment] 2019-05-22 18:35
I think this issue can be closed, because there are now definitions available. You can install them by running `npm i --save-dev @types/passport-google-oauth20`.  You can check their definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/passport-google-oauth20

If I have been missing something, just let me know and I will try to fix it.

**Comment by WORMSS** [comment] 2020-06-15 13:47
using definitelytyped is a workaround, not a fix.
If you add the correct `index.d.ts`, then definitelytyped doesn't have to be maintained externally.
index.d.ts is the preferred and recommended way.
definitelytyped is when original package maintainers have not provided any first-party support.

**Comment by aseerkt** [comment] 2020-11-20 16:17
`passport.use(
    new GoogleStrategy(
      {
        clientID: process.env.GOOGLE_CLIENT_ID!,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
        callbackURL: '/auth/google/callback',
      },
      async (_accessToken, _refreshToken, profile: Profile, done) => {
        try {
          const user = await User.findOne({ googleId: profile.id });
          if (user) {
            return done(undefined, user);
          }
          const newUser = await User.create({
            googleId: profile.id,
            displayName: profile.displayName,
            image: profile.photos[0].value,
          });
          return done(undefined, newUser);
        } catch (err) {
          return done(err, false);
        }
      }
    )
  );
`
Here I am getting typescript error when I user `profile.photos[0].value`, where actually `profile.photos` is **array** but typescript warning shows its an **object**.

**Comment by jaredhanson** [comment] 2021-11-13 00:00
Duplicate of #23.

**Comment by jaredhanson** [comment] 2021-11-13 00:01
Typings are available via an external package:

```sh
$ npm install @types/passport-google-oauth20
```

I have no current plans to maintain TypeScript definitions in this repository, as I am not a frequent user of TypeScript and thus don't want to maintain them.  External maintenance of typings by interested parties is preferred.

**Closed by jaredhanson** 2021-11-13 00:01 UTC
Labels: duplicate, enhancement
